name: NCTL Scan K8s Demo
run-name: ${{ github.actor }} has triggered Scan Action 🚀
on:
  pull_request:
    branches:
      - "main"

jobs:
  NCTL-Scan-K8s:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Download nctl artifact from go-nctl (NDEV-20537)
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GO_NCTL_READ_TOKEN }}
          repo: nirmata/go-nctl
          branch: NDEV-20537
          workflow: ci.yaml
          name: nctl-binary
          check_artifacts: true
          workflow_conclusion: ""

      - name: Install nctl
        run: |
          chmod +x nctl
          sudo mv nctl /usr/local/bin/nctl

      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: Check nctl version
        run: nctl version

      - name: Login to Nirmata
        run: |
          nctl login --url https://www.nirmata.io --userid dolis@nirmata.com --token ${{ secrets.NIRMATA_TOKEN }}

      - name: NCTL Scan - Kubernetes
        run: nctl scan kubernetes --resources config-files/k8s --publish --pipeline 0


      - run: echo "🍏 This job's status is ${{ job.status }}."
