name: NCTL Scan Supported Output Formats
run-name: ${{ github.actor }} has triggered Scan Action 🚀
on:
  # pull_request:
  #   types: [opened, reopened]
  push:
    branches:
      - "main"

jobs:
  Scan-Output-Formats:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: nctl-scan-installer
        uses: nirmata/action-install-nctl-scan@v0.0.4

      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: Check nctl version
        run: nctl version

      # - name: NCTL Scan - Concise Report
      #   run: nctl scan kubernetes --policies controls/pod-security --resources config-files/k8s --details --audit-as-warn

      # - name: NCTL Scan - Detailed Report
      #   run: nctl scan kubernetes --policies controls/pod-security --resources config-files/k8s --details --audit-as-warn

      # - name: NCTL Scan - JSON output
      #   run: nctl scan kubernetes --policies controls/pod-security --resources config-files/k8s --output json --audit-as-warn

      # - name: NCTL Scan - YAML output
      #   run: nctl scan kubernetes --policies controls/pod-security --resources config-files/k8s --output yaml

      # - name: NCTL Scan - SARIF output
      #   run: nctl scan kubernetes --policies controls/pod-security --resources config-files/k8s --output sarif --output results.sarif --audit-as-warn

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: report.sarif


      - run: echo "🍏 This job's status is ${{ job.status }}."
